function reac_out = reactor_effluent_stream(reac_state,influent,KLa,So_sat,parameters,V,dt)

    K_OH  = parameters(1);
    K_NO  = parameters(2);
    K_NHA = parameters(3);
    K_OA  = parameters(4);
    n_H   = parameters(5);
    Y_H   = parameters(6);
    i_NBM = parameters(7);
    Y_A   = 1/parameters(8);
    a3    = parameters(9);
    K_s   = parameters(10);
    f_p   = parameters(11);
    b_H   = parameters(12);
    b_A   = parameters(13);
    k_h   = parameters(14);
    K_x   = parameters(15);
    mu_H  = parameters(16);
    n_g   = parameters(17);
    mu_A  = parameters(18);

    Ss  = reac_state(1);
    Xs  = reac_state(3);
    Xbh = reac_state(3);
    Xba = reac_state(4);
    So  = reac_state(5);
    Sno = reac_state(6);
    Snh = reac_state(7);


    reac_out(1) = Ss + dt*((influent(end) / V) * influent(1) - (influent(end) / V) * Ss - ...
                                    (1.0 / Y_H) * ((mu_H * (Ss / (K_s + Ss)) * ...
                                    (So / (K_OH + So)) * Xbh) + ...
                                    (mu_H * (Ss / (K_s + Ss)) * ...
                                    (K_OH / (K_OH + So)) * (Sno / (K_NO + Sno)) * n_g * Xbh)) ...
                                               + (k_h * ((Xs / Xbh) / (K_x + ...
                                               (Xs / Xbh))) * ((So / (K_OH + So)) + ... 
                                               n_H * ((K_OH / (K_OH + So)) * (Sno / (K_NO + Sno))))) * Xbh);
    
    reac_out(2) = Xs + dt*((influent(end) / V) * influent(2) - (influent(end) / V) * Xs + ...
                           (1.0 - f_p) * (b_H * Xbh) + (1.0 - f_p) * (b_A * Xba) - ...
                               (k_h * ((Xs / Xbh) / (K_x + (Xs / Xbh))) * ...
                               ((So / (K_OH + So)) + n_H * ((K_OH / (K_OH + So)) * ...
                               (Sno / (K_NO + Sno))))) * Xbh);
    
    reac_out(3) = Xbh + dt*((influent(end) / V) * influent(3) - (influent(end) / V) * Xbh + ...
                            mu_H * (Ss / (K_s + Ss)) * ...
                                (So / (K_OH + So)) * Xbh + ...
                                        mu_H * (Ss / (K_s + Ss)) * ...
                                        (K_OH / (K_OH + So)) * (Sno / (K_NO + Sno)) * n_g * Xbh - b_H * Xbh);
    
    reac_out(4) = Xba + dt*((influent(end) / V) * influent(4) - (influent(end) / V) * Xba + ...
                            mu_A * (Snh / (K_NHA + Snh)) * ...
                            (So / (K_OA + So)) * Xba - b_A * Xba);

    reac_out(5) = So + dt*((influent(end) / V) * influent(5) - (influent(end) / V) * So - ...
                               ((1.0 - Y_H) / Y_H) * (mu_H * (Ss / (K_s + Ss)) * (So / (K_OH + So)) * Xbh) - ...
                               ((4.57 - Y_A) / Y_A) * (mu_A * (Snh / (K_NHA + Snh)) * ...
                                   (So / (K_OA + So)) * Xba) + ...
                                   KLa * (So_sat - So));

    reac_out(6) = Sno + dt*((influent(end) / V) * influent(6) - (influent(end) / V) * Sno - ...
                                ((1.0 - Y_H) / 2.86 * Y_H) * (mu_H * (Ss / (K_s + Ss)) * (K_OH / (K_OH + So)) * (Sno / (K_NO + Sno)) * n_g * Xbh) + ...
                                (1.0 / Y_A) * (mu_A * (Snh / (K_NHA + Snh)) * (So / (K_OA + So)) * Xba));
    
    reac_out(7) = Snh + dt*((influent(end) / V) * influent(7) - (influent(end) / V) * Snh - ...
                            i_NBM * (mu_H * (Ss / (K_s + Ss)) * (So / (K_OH + So)) * Xbh) - ...
                            i_NBM * (mu_H * (Ss / (K_s + Ss)) * (K_OH / (K_OH + So)) * (Sno / (K_NO + Sno)) * n_g * Xbh) - ...
                            (i_NBM + (1.0 / Y_A)) * (mu_A * (Snh / (K_NHA + Snh)) * (So / (K_OA + So)) * Xba) + ...
                            (a3 * Xbh));


end